### ISSUE TITLE
Automation disengage error

### ISSUE THREAD

**Issue by cameronangeli** [EnvelopSF/EnvelopLive#7]
when using midi clips to automate the location knobs on the maxforlive plugins, the automation becomes disengaged. this continues happening randomly. I cannot confirm what causes it to disengage (it's not just when it passes the -180 mark, to reset for full circles rotation, seems to be with random parameters, and random times). 

would really like to get this solved in the next couple weeks, because we have a few people planning to perform with this at Bman. Thanks!

**Comment by roddylindsay** [comment]
@cameronangeli this should be fixed in 6eb70
